Resources:
    Ec2Instance:
      Type: AWS::EC2::Instance
      Properties:
        InstanceType: t2.micro
        ImageId: ami-0db9040eb3ab74509
        Tags:
          - Key: Name
            Value: A simple example