apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: my-space
  labels:
    name: nginx
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"