apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    name: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: ront-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2